alias cda4='cd /opt/android4.0/'
alias cda2='cd /opt/android2.2/'
alias cda2a='cd /opt/android2.2-BSP12R_A1/'
alias gae-proxy='~/Downloads/goagent/local/proxy.py'

alias apti='apt-get install'
alias aptbi='apt-get -t squeeze-backports install'
alias aptei='apt-get -t experimental install'
alias apts='apt-cache search'
alias aptsh='apt-cache show'
